package bridge_test

import (
	"context"
	"encoding/json"
	"path/filepath"
	"testing"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/zyx1121/kitbash/internal/problem"
)

// What a Package generated by the import-cli kit declares as the output of
// every tool but probe, deploy/org/import-cli/generate.js. It is here in the
// shape a manifest carries it so that the bridge is exercised against the
// schema a generated Package really ships, issue #114; that the generator
// writes exactly this is the kit's own tests, which run in the kits CI job.
const generatedCLIOutput = `{
  "type": "object",
  "additionalProperties": false,
  "required": ["exitCode", "stdout", "stderr", "files", "truncated"],
  "properties": {
    "exitCode": { "type": ["integer", "null"] },
    "stdout": { "type": "string" },
    "stdoutJson": {},
    "stderr": { "type": "string" },
    "files": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["name"],
        "properties": {
          "name": { "type": "string" },
          "contentBase64": { "type": "string", "contentEncoding": "base64" },
          "path": { "type": "string" }
        }
      }
    },
    "notes": { "type": "array", "items": { "type": "string" } },
    "truncated": { "type": "boolean" },
    "signal": { "type": "string" },
    "timedOut": { "type": "boolean" }
  }
}`

// cliPackage is a Package whose one tool declares the schema import-cli
// generates instead of the harness's own.
func cliPackage(t *testing.T, answer mcp.ToolHandler) *harness {
	t.Helper()
	h := newHarness(t, answer)
	writeFile(t, filepath.Join(h.folder, "schemas", "transcode.out.json"), generatedCLIOutput)
	return h
}

// cliAnswer is what the generated adapter returns: the payload as
// structuredContent and the same JSON in a text block.
func cliAnswer(payload map[string]any) mcp.ToolHandler {
	return func(_ context.Context, _ *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		encoded, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		return &mcp.CallToolResult{
			Content:           []mcp.Content{&mcp.TextContent{Text: string(encoded)}},
			StructuredContent: json.RawMessage(encoded),
		}, nil
	}
}

func callCLI(t *testing.T, h *harness) *mcp.CallToolResult {
	t.Helper()
	h.run(t)
	s := h.connect(t)
	res, err := s.CallTool(context.Background(), &mcp.CallToolParams{
		Name:      "ffmpeg_transcode",
		Arguments: map[string]any{"path": "/org/media/clip.mov"},
	})
	if err != nil {
		t.Fatalf("calling the tool: %v", err)
	}
	return res
}

// A generated CLI Package answers structuredContent, and that is what the
// bridge checks against the output schema its manifest declares. The two
// branches are here together because they are the whole of the guarantee: what
// matches passes through, what drifted is an internal problem naming the
// Package.
func TestAGeneratedCLIPackageAnswerIsValidated(t *testing.T) {
	t.Run("the answer the adapter builds", func(t *testing.T) {
		res := callCLI(t, cliPackage(t, cliAnswer(map[string]any{
			"exitCode":  0,
			"stdout":    "{}",
			"stderr":    "",
			"files":     []any{map[string]any{"name": "out.json", "path": "/files/out/out.json"}},
			"truncated": false,
		})))
		if res.IsError {
			t.Fatalf("a generated answer was refused: %+v", res.Content)
		}
		if res.StructuredContent == nil {
			t.Fatal("the structured answer was dropped on the way out")
		}
		var out struct {
			ExitCode int    `json:"exitCode"`
			Stdout   string `json:"stdout"`
		}
		raw, err := json.Marshal(res.StructuredContent)
		if err != nil {
			t.Fatal(err)
		}
		if err := json.Unmarshal(raw, &out); err != nil {
			t.Fatalf("decoding %s: %v", raw, err)
		}
		if out.Stdout != "{}" {
			t.Errorf("the answer is %s, want the Package's own payload", raw)
		}
		// The text block travels with it, because a client that shows text is
		// the other half of why the adapter answers twice over.
		if len(res.Content) != 1 {
			t.Errorf("the result carries %d content blocks, want the one the adapter sent", len(res.Content))
		}
	})

	t.Run("an answer that drifted from the schema", func(t *testing.T) {
		// A killed command answers exitCode null and the generated schema
		// allows it; a string is a Package that stopped honouring its manifest.
		res := callCLI(t, cliPackage(t, cliAnswer(map[string]any{
			"exitCode":  "0",
			"stdout":    "",
			"stderr":    "",
			"files":     []any{},
			"truncated": false,
		})))
		p := problemOf(t, res)
		if p.Slug() != problem.SlugInternal {
			t.Errorf("problem is %s, want internal", p.Slug())
		}
		if p.Detail != "the Package returned output that does not match its manifest" {
			t.Errorf("detail is %q, want the manifest mismatch sentence", p.Detail)
		}
	})
}

// And the shape issue #114 reported: one text block for a tool whose manifest
// declares an output schema. The bridge passes it through, because prose is an
// answer and there is nothing to validate, so nothing here can catch a Package
// that stopped sending what it promised. That is why the fix is the adapter
// answering structuredContent and not a rule added to this file: a rule would
// refuse the Packages that legitimately answer in text.
func TestATextOnlyAnswerToACLIToolIsNotValidated(t *testing.T) {
	res := callCLI(t, cliPackage(t, func(_ context.Context, _ *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return &mcp.CallToolResult{
			Content: []mcp.Content{&mcp.TextContent{Text: `{"exitCode":"not an integer"}`}},
		}, nil
	}))
	if res.IsError {
		t.Fatalf("a text only answer was reported as an error: %+v", res.Content)
	}
	if res.StructuredContent != nil {
		t.Error("a text only answer gained structured content it never sent")
	}
}
